### PR TITLE
Filter ForwardAuth request headers

### LINKED ISSUE #7225: Problem with authentication multipart request
### What did you do?

I've configured [forward auth](https://github.com/nkonev/videochat/blob/traefik-multipart-repro/docker/traefik_conf/dynamic/gateway.yml#L67) in traefik. 
```yml
      forwardAuth:
        address: "http://api.site.local:8060/internal/profile"
        authResponseHeaders:
          - "X-Auth-Username"
          - "X-Auth-UserId"
          - "X-Auth-ExpiresIn"
          - "X-Auth-Role"
```

When I try to upload file a frontend [sents request](https://github.com/nkonev/videochat/blob/traefik-multipart-repro/frontend/src/ChooseAvatar.vue#L44) like below to the backend
```
curl 'http://localhost:8081/api/storage/avatar' -H 'User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3' --compressed -H 'X-XSRF-TOKEN: 443c72d5-234f-40fd-ba8e-6eb567590e04' -H 'Content-Type: multipart/form-data; boundary=---------------------------31244158103659301652102077701' -H 'Origin: http://localhost:8081' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: http://localhost:8081/' -H 'Cookie: Idea-71d2226b=ce2304b6-1f64-4e8b-8de5-3c03f71cddeb; Idea-1b0501e6=9a111b55-469c-456d-a539-2ab32fc85402; SESSION=MzQ4ZWEzYTQtMzBjZi00NTU1LWFlZjAtYmMzNWI5OTI0NjNk; XSRF-TOKEN=443c72d5-234f-40fd-ba8e-6eb567590e04' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-binary $'-----------------------------31244158103659301652102077701\r\nContent-Disposition: form-data; name="data"; filename="71fnx7xilML._SL1500_.jpg"\r\nContent-Type: image/jpeg\r\n\r\n-----------------------------31244158103659301652102077701--\r\n'
```

It becomes GET with Content-Type: multipart/form-data; because of [setting headers from original request to forwarded](https://github.com/containous/traefik/blob/29bd6faa18780623622e1688e86e00c0e4ba99f9/pkg/middlewares/auth/forward.go#L92), ... and goes to the authentication microservice. Authentication microservice logs
```
2020-08-29 04:08:29.501 [17 ms]
Request:
GET /internal/profile HTTP/1.1
host: api.site.local:8060
user-agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate
accept-language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
cache-control: no-cache
content-type: multipart/form-data; boundary=---------------------------354625936717211410991541674829
cookie: Idea-71d2226b=ce2304b6-1f64-4e8b-8de5-3c03f71cddeb; Idea-1b0501e6=9a111b55-469c-456d-a539-2ab32fc85402; m=2258:Z3Vlc3Q6Z3Vlc3Q%253D; SESSION=MzQ4ZWEzYTQtMzBjZi00NTU1LWFlZjAtYmMzNWI5OTI0NjNk; XSRF-TOKEN=443c72d5-234f-40fd-ba8e-6eb567590e04
dnt: 1
origin: http://localhost:8081
pragma: no-cache
referer: http://localhost:8081/
uber-trace-id: 33e9abbf356bb7c112cf38a56d53b92f:428da8cc00c3573e:12cf38a56d53b92f:1
x-forwarded-for: 172.28.0.1
x-forwarded-host: localhost:8081
x-forwarded-method: POST
x-forwarded-port: 8081
x-forwarded-proto: http
x-forwarded-server: traefik
x-forwarded-uri: /api/storage/avatar
x-real-ip: 172.28.0.1
x-xsrf-token: 443c72d5-234f-40fd-ba8e-6eb567590e04
```

Typical Servlet Container (Tomcat) cannot handle correctly GET request with `content-type: multipart/form-data;`, boundaries but **without body**, it tries to parse request parts and throws exception:
```
org.springframework.web.multipart.MultipartException: Failed to parse multipart servlet request; nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.FileUploadException: Stream closed
	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.handleParseFailure(StandardMultipartHttpServletRequest.java:124)
	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.parseRequest(StandardMultipartHttpServletRequest.java:115)
	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.<init>(StandardMultipartHttpServletRequest.java:88)
	at org.springframework.web.multipart.support.StandardServletMultipartResolver.resolveMultipart(StandardServletMultipartResolver.java:87)
	at org.springframework.web.servlet.DispatcherServlet.checkMultipart(DispatcherServlet.java:1178)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1012)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:160)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:141)
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.nkonev.aaa.config.TracerLoggingFilter.doFilter(TracerLoggingFilter.java:38)
	at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.opentracing.contrib.web.servlet.filter.TracingFilter.doFilter(TracingFilter.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at ch.qos.logback.access.servlet.TeeFilter.doFilter(TeeFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1674)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1104)
	at org.apache.tomcat.util.net.Nio2Endpoint.setSocketOptions(Nio2Endpoint.java:335)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:436)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:391)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: org.apache.tomcat.util.http.fileupload.FileUploadException: Stream closed
	at org.apache.catalina.connector.Request.parseParts(Request.java:2916)
	at org.apache.catalina.connector.Request.getParts(Request.java:2771)
	at org.apache.catalina.connector.RequestFacade.getParts(RequestFacade.java:1098)
	at javax.servlet.http.HttpServletRequestWrapper.getParts(HttpServletRequestWrapper.java:359)
	at javax.servlet.http.HttpServletRequestWrapper.getParts(HttpServletRequestWrapper.java:359)
	at javax.servlet.http.HttpServletRequestWrapper.getParts(HttpServletRequestWrapper.java:359)
	at javax.servlet.http.HttpServletRequestWrapper.getParts(HttpServletRequestWrapper.java:359)
	at javax.servlet.http.HttpServletRequestWrapper.getParts(HttpServletRequestWrapper.java:359)
	at javax.servlet.http.HttpServletRequestWrapper.getParts(HttpServletRequestWrapper.java:359)
	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.parseRequest(StandardMultipartHttpServletRequest.java:95)
	... 110 more
Caused by: org.apache.tomcat.util.http.fileupload.FileUploadException: Stream closed
	at org.apache.tomcat.util.http.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:308)
	at org.apache.catalina.connector.Request.parseParts(Request.java:2869)
	... 119 more
Caused by: java.io.IOException: Stream closed
	at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:359)
	at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:132)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.apache.tomcat.util.http.fileupload.util.LimitedInputStream.read(LimitedInputStream.java:132)
	at org.apache.tomcat.util.http.fileupload.MultipartStream$ItemInputStream.makeAvailable(MultipartStream.java:977)
	at org.apache.tomcat.util.http.fileupload.MultipartStream$ItemInputStream.read(MultipartStream.java:881)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at org.apache.tomcat.util.http.fileupload.util.Streams.copy(Streams.java:98)
	at org.apache.tomcat.util.http.fileupload.util.Streams.copy(Streams.java:68)
	at org.apache.tomcat.util.http.fileupload.MultipartStream.readBodyData(MultipartStream.java:572)
	at org.apache.tomcat.util.http.fileupload.MultipartStream.discardBodyData(MultipartStream.java:596)
	at org.apache.tomcat.util.http.fileupload.MultipartStream.skipPreamble(MultipartStream.java:614)
	at org.apache.tomcat.util.http.fileupload.impl.FileItemIteratorImpl.findNextItem(FileItemIteratorImpl.java:217)
	at org.apache.tomcat.util.http.fileupload.impl.FileItemIteratorImpl.<init>(FileItemIteratorImpl.java:131)
	at org.apache.tomcat.util.http.fileupload.FileUploadBase.getItemIterator(FileUploadBase.java:255)
	at org.apache.tomcat.util.http.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:279)
	... 120 more

```

### What did you expect to see?
I expect to have ability to configure traefik to send a correct request to the authentcation microservice.

### What did you see instead?
Exception above

### Output of `traefik version`: (_What version of Traefik are you using?_)
2.2.4

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
branch to reproduce https://github.com/nkonev/videochat/blob/traefik-multipart-repro/docker-compose.yml#L7

### PR DESCRIPTION
**Pull request by nkonev**
### What does this PR do?

Fixes #7225

### CODE REVIEW

**Comment by ldez** [comment]
Close to #6893

**Comment by nkonev** [comment]
@ldez 
I don't think so, that request about response meaders, my is about request headers passing to authentication microservice.

I have thought, it can be simplified - to set optional config paratmeter `requestContentType`. Yml example is `requestContentType: "application/json"`

**Comment by nkonev** [comment]
Perharps Content-Type header is not needed for the GET request without body according [spec](https://tools.ietf.org/html/rfc7231#section-3.1.1.5), so I simplefied this PR more

**Comment by rtribotte** [comment]
Hello @nkonev,

Thanks for your contribution !

Removing the `Content-Type` header would fix your issue, but it's also introducing a breaking change for those who may have rely on this header since now.
It's true that the RFC don't specify that a `Content-Type` header is mandatory for request that don't have body.
Since the authentication request is a GET, your were making a correct assumption, but it is also not illegal to have the `Content-Type` header in a GET request.

For that reason, we would not accept your proposal as it is.

Nevertheless, we think that you could address your issue by introducing an "allow-list" for headers to be transmitted to the authentication backend.
When no allow list is defined in the configuration, by default, all headers would be copied to the authentication request.
When the allow list is defined in the configuration, the request would contain only the headers allowed by the list.
It would work as the [authResponseHeaders](https://docs.traefik.io/v2.3/middlewares/forwardauth/#authresponseheaders) option.

Do you think that you can adapt your pull request to introduce that allow list option ?

**Comment by nkonev** [comment]
@rtribotte thank you for reply!
Yes, I can adapt this request to introduce that allow list option.

**Comment by nkonev** [comment]
@rtribotte done

File: pkg/middlewares/auth/forward.go [hunk 1]
```diff
@@ -158,7 +160,22 @@ func (fa *forwardAuth) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
...
+		headerKey := http.CanonicalHeaderKey(headerName)
+		if len(forwardRequestHeaders[headerKey]) > 0 {
+			filteredHeaders[headerKey] = append([]string(nil), forwardRequestHeaders[headerKey]...)
+		}
+	}
+	return filteredHeaders
+}
+
+func writeHeader(req, forwardReq *http.Request, trustForwardHeader bool, allowedHeaders []string) {
 	utils.CopyHeaders(forwardReq.Header, req.Header)
```
Comment (rtribotte) [inline pkg/middlewares/auth/forward.go:179]: I would apply the filtering before the `X-Forwarded-` headers handling.
It would guarantee their presence and allow the new `authRequestHeaders` option to not interfere with the `trustForwardHeader' option.
WDYT ?
(Unfortunately that imply to update your tests and also the documentation to use other examples)

```suggestion
	utils.CopyHeaders(forwardReq.Header, req.Header)
	forwardReq.Header = filterForwardRequestHeaders(forwardReq.Header, allowedHeaders)
```

File: pkg/middlewares/auth/forward.go [hunk 2]
```diff
@@ -214,4 +231,6 @@ func writeHeader(req, forwardReq *http.Request, trustForwardHeader bool) {
 	default:
 		forwardReq.Header.Del(xForwardedURI)
 	}
+
+	forwardReq.Header = filterForwardRequestHeaders(forwardReq.Header, allowedHeaders)
```
Comment (rtribotte) [inline pkg/middlewares/auth/forward.go:235]: Accordingly to the previous comment, those lines would be removed.
```suggestion
```

File: docs/content/middlewares/forwardauth.md [hunk 3]
```diff
@@ -217,6 +217,66 @@ http:
           - "X-Secret"
 ```
 
+### `authRequestHeaders`
+
+The `authRequestHeaders` option is the list of the headers to copy to the request to the authentication server.
+It can be used to prevent pass `Content-Type:multipart/form-data` header to the request to the authentication server
```
[the remark this answers is not in the document]
Comment (nkonev) [reply docs/content/middlewares/forwardauth.md:223]: I will rephrase, and, definitely, will write about empty list behaviour. I think statement about `Content-Type:multipart/form-data` would be helpful for those who is trying to google solution of his or her issue with the auth server.

File: pkg/middlewares/auth/forward.go (hunk 1 above)
Comment (nkonev) [reply pkg/middlewares/auth/forward.go:179]: I also was thinking what is best place for. Thank you for a good catch about trustForwardHeader option interference. I foing to do it.

The update tests for this particular case not a problem.

File: pkg/middlewares/auth/forward.go (hunk 2 above)
Comment (nkonev) [reply pkg/middlewares/auth/forward.go:235]: ok

File: pkg/middlewares/auth/forward_test.go [hunk 4]
```diff
@@ -368,6 +370,57 @@ func Test_writeHeader(t *testing.T) {
...
+			headers: map[string]string{
+				"X-CustomHeader": "CustomHeader",
+				"Content-Type":   "multipart/form-data; boundary=---123456",
+			},
+			authRequestHeaders: []string{
+				"X-CustomHeader",
+				"X-Forwarded-Proto",
+				"X-Forwarded-Host",
+				"X-Forwarded-Uri",
+				"X-Forwarded-Method",
```
Comment (rtribotte) [inline pkg/middlewares/auth/forward_test.go:406]:
```suggestion
```

**Review by rtribotte — CHANGES_REQUESTED** [review]

**Comment by nkonev** [comment]
so Semaphore is hanging ` Waiting for status to be reported`... for several days

**Comment by ldez** [comment]
could you rebase your PR, thank you.

**Comment by nkonev** [comment]
@ldez done.

I am not sure if Semaphore is really checking it.

**Comment by ldez** [comment]
Semaphore has a problem related to the organization's change, I'm going to have to close and then reopen your PR.
Sorry for the inconvenience.

**Review by rtribotte — APPROVED** [review]
LGTM 👌

**Comment by nkonev** [comment]
Hello, can we merge this PR ?
@ldez @rtribotte

**Review by ldez — APPROVED** [review]
Thanks :+1:

**Review by jbdoumenjou — APPROVED** [review]
LGTM
