### PR TITLE
Fix deny encoded characters

### LINKED ISSUE #12437: v3.6.5 breaks http.encodedCharacters.allowEncodedSlash
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

`http.encodedCharacters.allowEncodedSlash: true` seems to get ignored in v3.6.5. It works with v3.6.4.

### What did you see instead?

`traefik-1  | 2025-12-17T16:08:45Z DBG github.com/traefik/traefik/v3/pkg/server/router/deny.go:52 > Rejecting request because it contains encoded character %2F in the URL path: /api/v4/projects/[...]%2F[...]`

### What version of Traefik are you using?

```
# docker run traefik version
Version:      3.6.5
Codename:     ramequin
Go version:   go1.24.11
Built:        2025-12-16T14:56:48Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

traefik.yaml:
```yaml
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http3: {}
    http:
      encodedCharacters:
        allowEncodedSlash: true
```

### If applicable, please paste the log output in DEBUG level

_No response_

### PR DESCRIPTION
**Pull request by rtribotte**
### What does this PR do?

This PR fixes the encoded characters denial setup by using entryPoints models to create a unique router if the encoded characters denial configuration differs between entryPoints.

### Motivation

Fixes #12437

### More

- [x] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

Co-authored-by: Kevin Pollet <pollet.kevin@gmail.com>

### CODE REVIEW

**Review by juliens — APPROVED** [review]
LGTM

File: integration/simple_test.go [hunk 1]
```diff
@@ -2092,3 +2092,72 @@ func (s *SimpleSuite) TestSanitizePathSyntaxV2() {
 		}
 	}
 }
+
+// This test verifies that router handler caching does not interfere with
```
Comment (kevinpollet) [inline integration/simple_test.go]:
```suggestion
// TestEncodedCharactersDifferentEntryPoints verifies that router handler caching does not interfere with
```

File: pkg/config/dynamic/http_config.go [hunk 2]
```diff
@@ -71,11 +72,56 @@ type Router struct {
...
-	Observability *RouterObservabilityConfig `json:"observability,omitempty" toml:"observability,omitempty" yaml:"observability,omitempty" export:"true"`
-	DefaultRule   bool                       `json:"-" toml:"-" yaml:"-" label:"-" file:"-"`
+	RuleSyntax                  string                            `json:"ruleSyntax,omitempty" toml:"ruleSyntax,omitempty" yaml:"ruleSyntax,omitempty" export:"true"`
+	Priority                    int                               `json:"priority,omitempty" toml:"priority,omitempty,omitzero" yaml:"priority,omitempty" export:"true"`
+	TLS                         *RouterTLSConfig                  `json:"tls,omitempty" toml:"tls,omitempty" yaml:"tls,omitempty" label:"allowEmpty" file:"allowEmpty" kv:"allowEmpty" export:"true"`
+	Observability               *RouterObservabilityConfig        `json:"observability,omitempty" toml:"observability,omitempty" yaml:"observability,omitempty" export:"true"`
+	DefaultRule                 bool                              `json:"-" toml:"-" yaml:"-" label:"-" file:"-"`
+	DeniedEncodedPathCharacters RouterDeniedEncodedPathCharacters `json:"-" toml:"-" yaml:"-" label:"-" file:"-"`
+}
+
```
Comment (rtribotte) [inline pkg/config/dynamic/http_config.go:82]:
```suggestion

// +k8s:deepcopy-gen=true

```

**Review by lbenguigui — APPROVED** [review]
LGTM
