### PR TITLE
Fix panic for ingress with backend resource

### LINKED ISSUE #11772: v3.3.6 error: invalid memory address or nil pointer dereference
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have installed k3s version v1.32.4+k3s1 which automatically installs Traefik version 3.3.6. After a few hours of running my cluster fails: the k3s process exits because the machine is apparently overloaded. At that point, the `traefik` process uses 50-70% CPU and 3.4Gb of RAM (according to `top`), even though there is little to no traffic reaching the cluster (no applications installed, no users).

### What did you see instead?

Traefik's container log is filled with repeated "invalid memory address or nil pointer dereference" errors from its very beginning:
```
2025-05-19T15:48:36.422788666+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[32mINFESC[0m ESC[1mTraefik version 3.3.6 built on 2025-04-18T09:18:47ZESC[0m ESC[36mversion=ESC[0m3.3.6
2025-05-19T15:48:36.428436697+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[32mINFESC[0m ESC[1mStats collection is enabled.ESC[0m
2025-05-19T15:48:36.428698806+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[32mINFESC[0m ESC[1mMany thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration.ESC[0m
2025-05-19T15:48:36.428884509+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[32mINFESC[0m ESC[1mHelp us improve Traefik by leaving this feature on :)ESC[0m
2025-05-19T15:48:36.429046718+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[32mINFESC[0m ESC[1mMore details on: https://doc.traefik.io/traefik/contributing/data-collection/ESC[0m
2025-05-19T15:48:36.437659802+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[32mINFESC[0m ESC[1mStarting provider aggregator *aggregator.ProviderAggregatorESC[0m
2025-05-19T15:48:36.441228695+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[32mINFESC[0m ESC[1mStarting provider *traefik.ProviderESC[0m
2025-05-19T15:48:36.449219416+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[32mINFESC[0m ESC[1mStarting provider *acme.ChallengeTLSALPNESC[0m
2025-05-19T15:48:36.450353744+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[32mINFESC[0m ESC[1mStarting provider *ingress.ProviderESC[0m
2025-05-19T15:48:36.451014745+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[32mINFESC[0m ESC[1mingress label selector is: ""ESC[0m ESC[36mproviderName=ESC[0mkubernetes
2025-05-19T15:48:36.451173202+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[32mINFESC[0m ESC[1mCreating in-cluster Provider clientESC[0m ESC[36mproviderName=ESC[0mkubernetes
2025-05-19T15:48:36.463347884+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[32mINFESC[0m ESC[1mStarting provider *crd.ProviderESC[0m
2025-05-19T15:48:36.463790454+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[32mINFESC[0m ESC[1mlabel selector is: ""ESC[0m ESC[36mproviderName=ESC[0mkubernetescrd
2025-05-19T15:48:36.463833173+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[32mINFESC[0m ESC[1mCreating in-cluster Provider clientESC[0m ESC[36mproviderName=ESC[0mkubernetescrd
2025-05-19T15:48:36.779678211+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[31mERRESC[0m ESC[1mError in Go routineESC[0m ESC[36merror=ESC[0mESC[31mESC[1m"invalid memory address or nil pointer dereference"ESC[0mESC[0m
2025-05-19T15:48:36.782323663+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[31mERRESC[0m ESC[1mStack: goroutine 15 [running]:
2025-05-19T15:48:36.782395071+02:00 stdout F runtime/debug.Stack()
2025-05-19T15:48:36.782440283+02:00 stdout F    runtime/debug/stack.go:26 +0x5e
2025-05-19T15:48:36.78247843+02:00 stdout F github.com/traefik/traefik/v3/pkg/safe.defaultRecoverGoroutine({0x6b19bc0, 0xcf67190})
2025-05-19T15:48:36.782500948+02:00 stdout F    github.com/traefik/traefik/v3/pkg/safe/routine.go:65 +0x85
2025-05-19T15:48:36.782521902+02:00 stdout F github.com/traefik/traefik/v3/pkg/provider/kubernetes/ingress.(*Provider).Provide.func1.OperationWithRecover.3.1()
2025-05-19T15:48:36.782543469+02:00 stdout F    github.com/traefik/traefik/v3/pkg/safe/routine.go:73 +0x2f
2025-05-19T15:48:36.782574876+02:00 stdout F panic({0x6b19bc0?, 0xcf67190?})
2025-05-19T15:48:36.782596298+02:00 stdout F    runtime/panic.go:791 +0x132
2025-05-19T15:48:36.782617469+02:00 stdout F github.com/traefik/traefik/v3/pkg/provider/kubernetes/ingress.(*Provider).loadConfigurationFromIngresses(0xc000dc61a0, {0x8a1b020, 0xc000e089f0}, {0x8a33f38, 0xc00064b8f0})
2025-05-19T15:48:36.782638159+02:00 stdout F    github.com/traefik/traefik/v3/pkg/provider/kubernetes/ingress/kubernetes.go:320 +0x1532
2025-05-19T15:48:36.782667879+02:00 stdout F github.com/traefik/traefik/v3/pkg/provider/kubernetes/ingress.(*Provider).Provide.func1.1()
2025-05-19T15:48:36.782689012+02:00 stdout F    github.com/traefik/traefik/v3/pkg/provider/kubernetes/ingress/kubernetes.go:178 +0x2bd
2025-05-19T15:48:36.782710826+02:00 stdout F github.com/traefik/traefik/v3/pkg/provider/kubernetes/ingress.(*Provider).Provide.func1.OperationWithRecover.3()
2025-05-19T15:48:36.782731965+02:00 stdout F    github.com/traefik/traefik/v3/pkg/safe/routine.go:77 +0x52
2025-05-19T15:48:36.782762038+02:00 stdout F github.com/cenkalti/backoff/v4.RetryNotifyWithTimer.Operation.withEmptyData.func1()
2025-05-19T15:48:36.782786255+02:00 stdout F    github.com/cenkalti/backoff/v4@v4.3.0/retry.go:18 +0x13
2025-05-19T15:48:36.782807166+02:00 stdout F github.com/cenkalti/backoff/v4.doRetryNotify[...](0xc000eb9e70?, {0x89c06c0, 0xc000699c60}, 0xc000eb9ef8, {0x0, 0x0?})
2025-05-19T15:48:36.782827586+02:00 stdout F    github.com/cenkalti/backoff/v4@v4.3.0/retry.go:88 +0x11c
2025-05-19T15:48:36.782856853+02:00 stdout F github.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0xcf733b0?, {0x89c06c0?, 0xc000699c60?}, 0xc00016ad38?, {0x0?, 0x0?})
2025-05-19T15:48:36.782877656+02:00 stdout F    github.com/cenkalti/backoff/v4@v4.3.0/retry.go:61 +0x56
2025-05-19T15:48:36.782898572+02:00 stdout F github.com/cenkalti/backoff/v4.RetryNotify(...)
2025-05-19T15:48:36.782919101+02:00 stdout F    github.com/cenkalti/backoff/v4@v4.3.0/retry.go:49
2025-05-19T15:48:36.782987425+02:00 stdout F github.com/traefik/traefik/v3/pkg/provider/kubernetes/ingress.(*Provider).Provide.func1({0x8a1b058, 0xc00093bae0})
2025-05-19T15:48:36.783009398+02:00 stdout F    github.com/traefik/traefik/v3/pkg/provider/kubernetes/ingress/kubernetes.go:206 +0x208
2025-05-19T15:48:36.78302977+02:00 stdout F github.com/traefik/traefik/v3/pkg/safe.(*Pool).GoCtx.func1()
2025-05-19T15:48:36.783050244+02:00 stdout F    github.com/traefik/traefik/v3/pkg/safe/routine.go:36 +0x54
2025-05-19T15:48:36.783080034+02:00 stdout F github.com/traefik/traefik/v3/pkg/safe.GoWithRecover.func1()
2025-05-19T15:48:36.783100947+02:00 stdout F    github.com/traefik/traefik/v3/pkg/safe/routine.go:59 +0x4a
2025-05-19T15:48:36.783121637+02:00 stdout F created by github.com/traefik/traefik/v3/pkg/safe.GoWithRecover in goroutine 44
2025-05-19T15:48:36.783142692+02:00 stdout F    github.com/traefik/traefik/v3/pkg/safe/routine.go:53 +0x67
2025-05-19T15:48:36.783163594+02:00 stdout F ESC[0m
2025-05-19T15:48:36.783674947+02:00 stdout F ESC[90m2025-05-19T13:48:36ZESC[0m ESC[31mERRESC[0m ESC[1mProvider error, retrying in 585.151902msESC[0m ESC[36merror=ESC[0mESC[31mESC[1m"panic in operation: %!w(<nil>)"ESC[0mESC[0m ESC[36mproviderName=ESC[0mkubernetes
2025-05-19T15:48:37.573747947+02:00 stdout F ESC[90m2025-05-19T13:48:37ZESC[0m ESC[31mERRESC[0m ESC[1mError in Go routineESC[0m ESC[36merror=ESC[0mESC[31mESC[1m"invalid memory address or nil pointer dereference"ESC[0mESC[0m
[...]
```

### What version of Traefik are you using?

Traefik version 3.3.6 built on 2025-04-18T09:18:47Z

### What is your environment & configuration?

`/var/lib/rancher/k3s/server/manifests/traefik.yaml` as created by k3s:
```yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik-crd
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-crd-34.2.1+up34.2.0.tgz
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-34.2.1+up34.2.0.tgz
  set:
    global.systemDefaultRegistry: ""
  valuesContent: |-
    deployment:
      podAnnotations:
        prometheus.io/port: "8082"
        prometheus.io/scrape: "true"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: "system-cluster-critical"
    image:
      repository: "rancher/mirrored-library-traefik"
      tag: "3.3.6"
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    service:
      ipFamilyPolicy: "PreferDualStack"
```

single-node k8s cluster with single-stack IPv6 networking, no IPv4.

### If applicable, please paste the log output in DEBUG level

_No response_

### PR DESCRIPTION
**Pull request by rtribotte**
### What does this PR do?

This PR fixes a panic when an ingress defines a backend resource but not backend service.

### Motivation

Fixes #11772

### More

- [x] Added/updated tests
- [ ] Added/updated documentation

### Additional Notes

Co-authored-by: Kevin Pollet <pollet.kevin@gmail.com>

### CODE REVIEW

File: pkg/provider/kubernetes/ingress/kubernetes.go [hunk 1]
```diff
@@ -315,6 +315,12 @@ func (p *Provider) loadConfigurationFromIngresses(ctx context.Context, client Cl
...
 			for _, pa := range rule.HTTP.Paths {
+				if pa.Backend.Resource != nil {
+					// https://kubernetes.io/docs/concepts/services-networking/ingress/#resource-backend
+					logger.Error().Msg("Resource backends are not supported")
+					continue
+				}
+
 				service, err := p.loadService(client, ingress.Namespace, pa.Backend)
 				if err != nil {
 					logger.Error().
```
Comment (brandond) [inline pkg/provider/kubernetes/ingress/kubernetes.go:326]: Probably still shouldn't assume that pa.Backend.Service is non-nil here, even with the check for pa.Backend.Resource above.

Comment (rtribotte) [reply pkg/provider/kubernetes/ingress/kubernetes.go:331]: Thanks for pointing this out, we pushed a review commit for avoiding confusion and improve readability, but this case should never happen, as such an Ingress is invalid and this error should be raised: 
```The Ingress “ingress” is invalid: spec.rules[0].http.paths[0].backend: Invalid value: “”: resource or service backend is required```

**Review by sdelicata — APPROVED** [review]
LGTM

**Review by lbenguigui — APPROVED** [review]
LGTM
