### PR TITLE
Fix plugin type on middleware endpoint response

### LINKED ISSUE #7778: Custom middleware misses type in dashboard
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Added a custom plugin using custom middleware and opened the Traefik dashboard to view the custom middleware.

### What did you expect to see?
A custom middleware type defined by the plugin developer or at least something like 'Custom'

### What did you see instead?
Empty middleware type

image

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.7
Codename:     picodon
Go version:   go1.15.6
Built:        2021-01-11T18:03:02Z
OS/Arch:      linux/amd64
```

### PR DESCRIPTION
**Pull request by jspdown**
### What does this PR do?

This PR fixes a bug on the `/api/http/middlewares/{middlewareID}` endpoint when the requested middleware is a plugin. In this case the response didn't return the plugin type but instead an empty string.

### Motivation

Fixes #7778

### More

- [x] Added/updated tests
- [ ] ~Added/updated documentation~

### CODE REVIEW

File: pkg/api/handler.go [hunk 1]
```diff
@@ -157,6 +158,14 @@ func extractType(element interface{}) string {
 	v := reflect.ValueOf(element).Elem()
 	for i := 0; i < v.NumField(); i++ {
 		field := v.Field(i)
+
+		if field.Kind() == reflect.Map && field.Type().Elem() == reflect.TypeOf(dynamic.PluginConf{}) {
+			keys := field.MapKeys()
+			if len(keys) == 1 {
```
Comment (dtomcej) [inline pkg/api/handler.go:164]: can `keys` only have 0 or 1 entries? is it possible to have 2?

what about:
```
if keys := field.MapKeys(); len(keys) > 0 {
  return keys[0].String()
}
```

Comment (jspdown) [reply pkg/api/handler.go:164]: If misconfigured it can indeed be 0 or greater than 1. But if there's more than one plugin in the `PluginConf` it's going to be considered invalid. So, I think we shouldn't return any type for this middleware.

Comment (dtomcej) [reply pkg/api/handler.go:164]:
```suggestion
if keys := field.MapKeys(); len(keys) == 1 {
  return keys[0].String()
}```

File: pkg/api/handler.go [hunk 2]
```diff
@@ -157,6 +158,14 @@ func extractType(element interface{}) string {
...
+				return keys[0].String()
+			}
```
Comment (dtomcej) [inline pkg/api/handler.go:166]:
```suggestion
			if keys := field.MapKeys(); len(keys) == 1 {
				return keys[0].String()
			}
```

**Review by dtomcej — APPROVED** [review]
LGTM
:shipit:

**Review by rtribotte — APPROVED** [review]
LGTM 👍

**Review by ldez — APPROVED** [review]
LGTM
